<a href="https://colab.research.google.com/github/Srikanth9142/ML-works/blob/master/two%20language%20classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import os 
import scipy.io.wavfile as wav
import scipy.io.wavfile
import contextlib
import wave
import numpy as np
from tqdm import tqdm

In [4]:
from keras.optimizers import Adam
from keras import applications
from keras.models import Sequential
from keras.layers import Activation
from keras.layers import Dense, Dropout, Activation, Flatten, Add, BatchNormalization,AveragePooling2D
from keras.layers import Convolution2D, MaxPooling2D
from keras.layers import GlobalAveragePooling2D,Dropout,Dense
from keras.models import Model

Using TensorFlow backend.


In [5]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [6]:
pip install python_speech_features

  Created wheel for python-speech-features: filename=python_speech_features-0.6-cp36-none-any.whl size=5887 sha256=47f754626ac3d3c214dca774860dbcfb6d3c0ac60ea9c5ef6d5e2c220015efb6
  Stored in directory: /root/.cache/pip/wheels/3c/42/7c/f60e9d1b40015cd69b213ad90f7c18a9264cd745b9888134be
Successfully built python-speech-features


In [0]:
from python_speech_features import mfcc

This is attempt2 of Language Classification using data from [link text](http://festvox.org/h2r_indic/) and using default mfcc from python_speech_features

In [0]:
pre_emphasis = 0.97
frame_size = 0.025
frame_stride = 0.01
NFFT = 512
nfilt = 40
num_ceps = 12
cep_lifter =22

In [0]:
def length_audio(folder_name,file_name):
  file_path='/content/drive/My Drive/LC attempt2/'+str(folder_name)+"/"+str(file_name)
  sample_rate, signal = scipy.io.wavfile.read(file_path)
  with contextlib.closing(wave.open(file_path,'r')) as f:
      frames = f.getnframes()
      rate = f.getframerate()
      duration = frames / float(rate)
  return int(duration)

In [0]:
telugu_train_list = os.listdir('/content/drive/My Drive/LC attempt2/TELUGU_TRAIN')
telugu_test_list = os.listdir('/content/drive/My Drive/LC attempt2/TELUGU_TEST')
hindi_train_list = os.listdir('/content/drive/My Drive/LC attempt2/HINDI_TRAIN')
hindi_test_list = os.listdir('/content/drive/My Drive/LC attempt2/HINDI_TEST')

In [11]:
print(len(telugu_train_list))
print(len(telugu_test_list))
print(len(hindi_train_list))
print(len(hindi_test_list))

926
309
2145
715


In [12]:
mfcc_array=[]
for k in tqdm(range(len(telugu_train_list))):
  #len_audio = length_audio('TELUGU_TRAIN',telugu_train_list[k])
  rate,signal = wav.read('/content/drive/My Drive/LC attempt2/TELUGU_TRAIN/'+telugu_train_list[k])
  mfcc_features = mfcc(signal,rate)
  mfcc_array.append(mfcc_features)

100%|██████████| 926/926 [05:47<00:00,  3.31it/s]


In [13]:
print(len(mfcc_array))

926


In [14]:

for k in tqdm(range(926)):
  #len_audio = length_audio('HINDI_TRAIN',hindi_train_list[k])
  rate,signal = wav.read('/content/drive/My Drive/LC attempt2/HINDI_TRAIN/'+hindi_train_list[k])
  mfcc_features = mfcc(signal,rate)
  mfcc_array.append(mfcc_features)


100%|██████████| 926/926 [04:50<00:00,  3.37it/s]


In [15]:
len(mfcc_array)

1852

In [0]:

y_train=np.zeros((1852,2))
for i in range(1852):
  if(i<926):
    y_train[i][0] = 1
    y_train[i][1] = 0
  else:
    y_train[i][0] = 0
    y_train[i][1] = 1

In [17]:
y_train

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [18]:
type(y_train)

numpy.ndarray

In [19]:
X_train = np.zeros((1852,199,13))
for i in tqdm(range(len(mfcc_array))):
  for j in range(199):
    for k in range(13):
      X_train[i][j][k] = mfcc_array[i][j][k]

100%|██████████| 1852/1852 [00:03<00:00, 478.37it/s]


In [20]:
type(X_train)
X_train.shape

(1852, 199, 13)

In [21]:
mfcc_test_array=[]
for k in tqdm(range(309)):
  #len_audio = length_audio('TELUGU_TRAIN',telugu_train_list[k])
  rate,signal = wav.read('/content/drive/My Drive/LC attempt2/TELUGU_TEST/'+telugu_test_list[k])
  mfcc_features = mfcc(signal,rate)
  mfcc_test_array.append(mfcc_features)

100%|██████████| 309/309 [01:43<00:00,  2.87it/s]


In [0]:
#199X13 -->309  618

In [22]:
for k in tqdm(range(309)):
  #len_audio = length_audio('TELUGU_TRAIN',telugu_train_list[k])
  rate,signal = wav.read('/content/drive/My Drive/LC attempt2/HINDI_TEST/'+hindi_test_list[k])
  mfcc_features = mfcc(signal,rate)
  mfcc_test_array.append(mfcc_features)

100%|██████████| 309/309 [01:37<00:00,  3.43it/s]


In [23]:
len(mfcc_test_array)

618

In [24]:
x_test = np.zeros((618,199,13))
for i in tqdm(range(len(mfcc_test_array))):
  for j in range(199):
    for k in range(13):
      x_test[i][j][k] = mfcc_test_array[i][j][k]

100%|██████████| 618/618 [00:01<00:00, 465.59it/s]


In [25]:
type(x_test)

numpy.ndarray

In [0]:
y_test=[]
for i in range(309):
  y_test.append([1,0])
for i in range(309):
  y_test.append([0,1])
y_test_reshaped = np.zeros((618,2))
for i in range(309):
  y_test_reshaped[i][0] = 1
  y_test_reshaped[i][1] = 0
for i in range(309,618):
  y_test_reshaped[i][0] = 0
  y_test_reshaped[i][1] =1

In [39]:
y_test = np.asarray(y_test)
type(y_test)
print(y_test_reshaped.shape)
print(y_train.shape)

(618, 2)
(1852, 2)


In [28]:
X_train_reshaped = X_train.reshape(X_train.shape[0],199,13,1)
print(X_train_reshaped.shape)
x_test_reshaped = x_test.reshape(x_test.shape[0],199,13,1)
print(x_test_reshaped.shape)

(1852, 199, 13, 1)
(618, 199, 13, 1)


In [0]:
from keras.layers import Convolution2D, MaxPooling2D
from keras.layers.convolutional import Conv2D


In [0]:
####Trying with resnet50  

In [0]:
model = Sequential()
model.add(Conv2D(100,kernel_size=(3, 3),activation='relu',input_shape=(199,13,1)))
model.add(Dropout(0.25))
model.add(Dense(50, activation='relu'))
model.add(Dense(25,activation='relu'))
model.add(Dense(13,activation='relu'))
model.add(Dense(5,activation='relu'))
model.add(Flatten())
model.add(Dense(2,activation='softmax'))
adam=Adam(lr=0.0001)
model.compile(optimizer=adam,loss='categorical_crossentropy',metrics=['accuracy'])

In [45]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 197, 11, 100)      1000      
_________________________________________________________________
dropout_3 (Dropout)          (None, 197, 11, 100)      0         
_________________________________________________________________
dense_11 (Dense)             (None, 197, 11, 50)       5050      
_________________________________________________________________
dense_12 (Dense)             (None, 197, 11, 25)       1275      
_________________________________________________________________
dense_13 (Dense)             (None, 197, 11, 13)       338       
_________________________________________________________________
dense_14 (Dense)             (None, 197, 11, 5)        70        
_________________________________________________________________
flatten_2 (Flatten)          (None, 10835)            

In [49]:
print(y_train)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]


In [46]:
print(X_train_reshaped.shape)
print(y_train.shape)

(1852, 199, 13, 1)
(1852, 2)


In [47]:
model.fit(X_train_reshaped,y_train,epochs=20,validation_data=(x_test_reshaped,y_test_reshaped))

Train on 1852 samples, validate on 618 samples
Epoch 1/20
1852/1852 [==============================] - 7s 4ms/step - loss: 0.4602 - acc: 0.8051 - val_loss: 0.0476 - val_acc: 0.9968
Epoch 2/20
1852/1852 [==============================] - 1s 333us/step - loss: 0.0401 - acc: 0.9914 - val_loss: 0.0060 - val_acc: 1.0000
Epoch 3/20
1852/1852 [==============================] - 1s 361us/step - loss: 0.0124 - acc: 0.9978 - val_loss: 0.0015 - val_acc: 1.0000
Epoch 4/20
1852/1852 [==============================] - 1s 364us/step - loss: 0.0072 - acc: 0.9984 - val_loss: 8.6700e-04 - val_acc: 1.0000
Epoch 5/20
1852/1852 [==============================] - 1s 346us/step - loss: 0.0031 - acc: 1.0000 - val_loss: 4.7335e-04 - val_acc: 1.0000
Epoch 6/20
1852/1852 [==============================] - 1s 353us/step - loss: 0.0026 - acc: 0.9995 - val_loss: 3.1181e-04 - val_acc: 1.0000
Epoch 7/20
1852/1852 [==============================] - 1s 351us/step - loss: 0.0022 - acc: 0.9995 - val_loss: 1.5320e-04 - val

In [0]:
result = model.predict(x_test_reshaped) ##Means TElugu

In [51]:
result

array([[1.0000000e+00, 2.4138371e-08],
       [9.9999988e-01, 9.2545413e-08],
       [1.0000000e+00, 6.9303372e-09],
       ...,
       [9.2170080e-07, 9.9999905e-01],
       [2.2159403e-08, 1.0000000e+00],
       [1.4267719e-09, 1.0000000e+00]], dtype=float32)

In [52]:
result.shape

(618, 2)

In [55]:
prediction(result)

[309.0078345435679, 308.9921667754347]
Accent:  telugu
50.00% -> telugu
50.00% -> hindi


In [0]:
def prediction(targ):
    accents = ['telugu','hindi']
    np.set_printoptions(formatter={'float_kind':'{:.1f}'.format})
    #np.set_printoptions(formatter={'float_kind':'{:.1f}'.format})
    l=[]
    out_len = len(targ)
    in_len = len(targ[0])
    for i in range(in_len):
        sumi = 0
        for j in range(out_len):
            sumi+=targ[j][i]
        l.append(sumi)
    print(l)
    maximum = -1
    max_ind = -1
    for i in range(len(l)):
        if(l[i] > maximum):
            maximum = l[i]
            max_ind = i+1
    # print(maximum, max_ind)
    print("Accent: ",accents[max_ind-1])
    for i in l:
        if i!=0:
            per = (i/float(out_len))*100
            if(per>1):
                print("{1:.2f}% -> {0}".format(accents[l.index(i)],per))

In [0]:
###Rough by srikanth
filename = 'modifiedtharak.wav'
leng = length_audio('Manual_Testing',filename)
rate,signal=wav.read('/content/drive/My Drive/LC attempt2/Manual_Testing/'+filename)


In [57]:
a = 32000
len(signal[a:a+a])

28075

In [0]:

b=0
a=32000
count=0
manual_mfcc_array=[]
while(b<len(signal)):
  count+=1
  manual_mfcc_array.append(mfcc(signal[b:a],rate))
  b+=32000
  a+=32000



In [59]:
len(manual_mfcc_array[0])



199

In [0]:
input_arr = np.zeros((count,199,13))
for i in range(1):
  for j in range(199):
    for k in range(13):
      input_arr[i][j][k] = manual_mfcc_array[i][j][k]
input_arr_modified = input_arr.reshape(input_arr.shape[0],199,13,1)

In [0]:
result1=model.predict(input_arr_modified)

In [62]:
result1

array([[0.0, 1.0],
       [0.5, 0.5]], dtype=float32)

In [63]:
prediction(result1)

[0.5331561325442635, 1.466843843460083]
Accent:  hindi
26.66% -> telugu
73.34% -> hindi
